- job:
    name: build-app
    display-name: Build application
    project-type: pipeline
    description: Builds the application artefact and uploads it to S3
    disabled: false
    concurrent: true
    parameters:
      - choice:
          name: APPLICATION_NAME
          choices:
{% for application in dm_applications %}
            - {{ application }}
{% endfor %}
      - string:
          name: RELEASE_NAME
          description: "Application tag (eg 'release-42') to checkout for building the artefact"
    pipeline:
      script: |
        node {
            try {
                stage('Check previous builds') {
                  currentBuild.displayName = "#${BUILD_NUMBER} - ${APPLICATION_NAME} - ${RELEASE_NAME}"
                  existingRelease = sh(script: "aws s3 ls s3://digitalmarketplace-deployment/${APPLICATION_NAME}/${RELEASE_NAME}.zip", returnStatus: true)
                }

                if (existingRelease == 0) {
                  echo "Release ${RELEASE_NAME} already exists"
                  currentBuild.result = 'SUCCESS'
                  return
                }

                stage('Prepare') {
                    git url: "git@github.com:alphagov/digitalmarketplace-${APPLICATION_NAME}.git", branch: 'master', credentialsId: 'github_com_and_gds'
                    echo "Cleaning repository"
                    sh("git clean -fdx")
                    echo "Checking out ${RELEASE_NAME}"
                    sh("git reset --hard ${RELEASE_NAME}")
                }
                stage('Build') {
                    sh("git archive --format=zip HEAD > ${RELEASE_NAME}.zip")
                    if (fileExists('scripts/build.sh')) {
                        echo "Running build script.."
                        def includeDirs = sh(
                            script: "./scripts/build.sh",
                            returnStdout: true
                        ).trim()
                        echo "Adding directories to the build artefact:\n${includeDirs}"
                        for (dir in includeDirs.tokenize("\n")) {
                            sh("zip -r ${RELEASE_NAME}.zip ${dir}")
                        }
                    }
                    echo "Version label: ${RELEASE_NAME}"
                    sh("echo '${RELEASE_NAME}' > version_label")
                    sh("zip ${RELEASE_NAME}.zip version_label")
                    sh("git rev-parse HEAD > version_sha")
                    sh("zip ${RELEASE_NAME}.zip version_sha")
                }
                stage('Upload') {
                    sh("aws s3 cp --only-show-errors ${RELEASE_NAME}.zip s3://digitalmarketplace-deployment/${APPLICATION_NAME}/${RELEASE_NAME}.zip")
                }
            } catch(err) {
                currentBuild.result = 'FAILURE'
                echo "Error: ${err}"
            } finally {
            }
        }
