{% set environments = ['production'] %}
---
{% for environment in environments %}
- job:
    name: "notify-suppliers-whether-application-made-for-framework-{{ environment }}"
    display-name: "Notify suppliers whether application made for framework - {{ environment }}"
    project-type: freestyle
    description: "Send email notifications to supplier users indicating whether or not they completed an application for a framework."
    disabled: true
    parameters:
      - bool:
          name: DRY_RUN
          default: true
          description: "List notifications that would be sent without sending the emails"
      - string:
          name: FRAMEWORK_SLUG
          description: "The framework slug for which applications have just closed (e.g. g-cloud-10)."
    publishers:
      - trigger-parameterized-builds:
          - project: notify-slack
            condition: SUCCESS
            predefined-parameters: |
              USERNAME=${FRAMEWORK_SLUG}-applications
              JOB=Notify suppliers whether application made for framework - {{ environment }}
              ICON=:successkid:
              STAGE={{ environment }}
              STATUS=SUCCESS
              URL=<${BUILD_URL}consoleFull|#${BUILD_NUMBER}>
              CHANNEL=#dm-release
          - project: notify-slack
            condition: UNSTABLE_OR_WORSE
            predefined-parameters: |
              USERNAME=${FRAMEWORK_SLUG}-applications
              JOB=Notify suppliers whether application made for framework - {{ environment }}
              ICON=:question:
              STAGE={{ environment }}
              STATUS=FAILED
              URL=<${BUILD_URL}consoleFull|#${BUILD_NUMBER}>
              CHANNEL=#dm-release
    builders:
      - shell: |
          if [ "$DRY_RUN" = "true" ]; then
            FLAGS="$FLAGS --dry-run"
          fi

          docker run digitalmarketplace/scripts scripts/notify-suppliers-whether-application-made-for-framework.py "{{ environment }}" "$FRAMEWORK_SLUG" "$NOTIFY_API_TOKEN" $FLAGS
{% endfor %}
