- job:
    name: publish-framework-application-guidance
    display-name: Publish framework application guidance
    project-type: pipeline
    description: |
      Builds digitalmarketplace-framework-application-guidance and publishes it on Github Pages
    disabled: false
    concurrent: false
    triggers:
      - pollscm: "* * * * *"
    pipeline:
      script: |
        node {
          stage('Prepare') {
            git url: "git@github.com:alphagov/digitalmarketplace-framework-application-guidance.git", branch: 'master', credentialsId: 'github_com_and_enterprise'
            sh("rbenv install -s")
            sh("gem install bundler --conservative")
            sh("make requirements")
          }

          stage('Build and publish') {
            sh("git config user.name 'Jenkins'")
            sh("git config user.email '{{ jenkins_github_email }}'")
            sh("make publish")
          }
        }
