---
- hosts: jenkins_dmp_so
  name: Setup Jenkins CI, config and dependencies
  remote_user: ubuntu
  become: yes
  roles:
    - jenkins
    - role: willshersystems.sshd
      tags: [sshd, jenkins]
  vars:
    sshd:
      ClientAliveCountMax: 80
      ClientAliveInterval: 45
      LogLevel: VERBOSE
      PasswordAuthentication: no
      PermitRootLogin: no
      X11Forwarding: no
