---
- set_fact:  # The authorized_key module does accept URLs, but only one at a time when passed a multiline set of
             # keys, so we have to do the lookup ourselves and build a list of all the keys we want.
    ssh_keys: "{{ ssh_keys|default([jenkins_public_key])
      + query('url', 'https://github.com/' ~ item.name ~ '.keys', split_lines=True) }}"
  with_items:
    - "{{ jenkins_github_users }}"
  tags: keys

- name: Add developers' public ssh keys to authorized_keys file
  authorized_key:
    key: "{{ ssh_keys|join('\n') }}"
    user: ubuntu
    exclusive: yes
  tags: keys

- name: Setup Jenkins SSH directory
  file: path=/home/jenkins/.ssh state=directory owner=jenkins group=jenkins

- name: Setup Jenkins SSH config
  copy: src=jenkins_ssh_config dest=/home/jenkins/.ssh/config owner=jenkins mode=600

- name: Decrypt Github key for jenkins user
  become: no
  local_action: >  # TODO the following can cause a new 2FA request so should be refactored so the data is passed in on the command line
    shell {{ dm_credentials_repo }}/sops-wrapper -d {{ dm_credentials_repo }}/github/github_com_and_enterprise.enc >
    {{ dm_credentials_repo }}/github/github_com_and_enterprise &&
    chmod 600 {{ dm_credentials_repo }}/github/github_com_and_enterprise

- name: Copy Github keys for jenkins user
  copy: src={{ item.from }} dest=/home/jenkins/.ssh/{{ item.to }} mode=600 owner=jenkins
  with_items:
    - { from: "{{ dm_credentials_repo }}/github/github_com_and_enterprise", to: "github_com_and_enterprise" }

- name: Remove decrypted Github key for jenkins user
  become: no
  local_action: "shell rm {{ dm_credentials_repo }}/github/github_com_and_enterprise"

- name: ensure known hosts file exists for jenkins  # known_hosts directive doesn't seem to work
  copy:
    content: |
      github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    dest: /home/jenkins/.ssh/known_hosts
    force: no
    group: jenkins
    owner: jenkins
    mode: ug+rw
