---
- name: Add Docker APT repository key
  tags: [apt]
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install or update docker package
  apt:
    name: "docker-ce"
    state: latest
    update_cache: yes

- name: Create docker user group
  group: name=docker

- name: Add jenkins user to the docker group
  user:
    name: jenkins
    groups: [docker]
    append: yes
  notify: restart docker

- name: Create docker image graph/cache directory
  file: path=/data/docker mode=0700 state=directory owner=root

- name: Copy Docker daemon config file
  copy: src=docker_daemon.json dest=/etc/docker/daemon.json owner=root mode=0600
  notify: restart docker
