---

- name: Install gdrive (google drive command line interface client)
  get_url:
    url: "https://drive.google.com/uc?id=1Ej8VgsW5RgK66Btb9p74tSdHMH3p4UNb&export=download"
    dest: /usr/local/bin/gdrive
    checksum: sha1:6ef7c740e980358a9a5de36c1aac7ea375319aa3
    mode: 0755

- name: Add local .gdrive directory
  file: path=/var/lib/jenkins/.gdrive state=directory owner=jenkins group=jenkins

- name: Create token_v2.json file in .gdrive directory
  template: src=gdrive_token_v2.json.j2 dest=/var/lib/jenkins/.gdrive/token_v2.json owner=jenkins group=jenkins mode=600
