---

- name: Install gdrive (google drive command line interface client)
  get_url:
    url: "https://raw.githubusercontent.com/AnimMouse/gdrive-binaries/master/linux/gdrive-linux-x64"
    dest: /usr/local/bin/gdrive
    checksum: sha1:4fd8391b300cac45963e53da44dcfe68da08d843
    mode: 0755

- name: Add local .gdrive directory
  file: path=/var/lib/jenkins/.gdrive state=directory owner=jenkins group=jenkins

- name: Create token_v2.json file in .gdrive directory
  template: src=gdrive_token_v2.json.j2 dest=/var/lib/jenkins/.gdrive/token_v2.json owner=jenkins group=jenkins mode=600
