---
- name: Install Nginx
  apt: name=nginx update_cache=yes state=present

- name: Make sure nginx user is in www-data
  user: name=nginx groups=www-data

- name: Create nginx jenkins proxy configuration files
  template: src=jenkins_nginx.j2
            dest=/etc/nginx/sites-available/jenkins
            backup=yes
  notify: reload nginx

- name: Ensure that the default site is disabled
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
  notify: reload nginx

- name: Ensure that the configuration files are enabled
  command: ln -s /etc/nginx/sites-available/jenkins
           /etc/nginx/sites-enabled/jenkins
           creates=/etc/nginx/sites-enabled/jenkins
  notify: reload nginx
