---

- name: Download CloudFoundry Debian package
  get_url:
    url: "https://packages.cloudfoundry.org/stable?release=debian64&version=6.32.0&source=github-rel"
    dest: /tmp/cloudfoundry-cli.deb

- name: Install CloudFoundry CLI
  apt:
    deb: /tmp/cloudfoundry-cli.deb
