---
- name: Install OpenJDK JRE 8
  apt: name=openjdk-8-jre state=latest update_cache=yes
  notify:
    - restart jenkins

- name: Accept Microsoft core fonts EULA
  tags: [apt]
  shell: 'echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections'

- name: Add key for Postgres repo
  tags: [apt]
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Add Postgres repo to sources list
  tags: [apt]
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' state=present

- name: Add key for Chrome repo
  tags: [apt]
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Add Chrome repo to sources list
  tags: [apt]
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Install Chromedriver binary
  tags: [apt]
  unarchive:
    src: "https://chromedriver.storage.googleapis.com/98.0.4758.80/chromedriver_linux64.zip"
    dest: /usr/local/bin
    mode: 0755
    remote_src: yes

- name: Install tools
  tags: [apt]
  apt:
    update_cache: yes
    state: present
    name: "{{ dist_tools_unpinned + dist_tools_pinned }}"
  notify:
    - restart jenkins

- name: Install pinned dist packages
  tags: [apt]
  apt:
    update_cache: yes
    state: present
    name:
      - nodejs=10.*

- name: Install wkhtmltopdf with patched qt
  tags: [apt]
  apt:
    deb: https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.{{ ansible_distribution_release }}_amd64.deb
    state: present

- name: Update Python 3 pip
  pip:
    name:
      - pip
    state: latest

- name: Install AWS cli
  pip:
    name: awscli==1.19.110
    state: present

- name: Create AWS cli config folder
  file:
    path: ~/.aws
    state: directory
    owner: jenkins
    group: jenkins
    mode: u=rwx
  become: true
  become_user: jenkins

- name: Create AWS cli config file
  template:
    src: aws_config.j2
    dest: ~/.aws/config
    owner: jenkins
    group: jenkins
    mode: u=rw
  become: true
  become_user: jenkins
  vars:
    assume_cloudtrail_roles: "{{ cloudtrail_validate_logs_roles }}"
    assume_infrastructure_roles: "{{ aws_infrastructure_roles }}"

- name: Add gpg-agent conf directory
  file:
    path: /home/jenkins/.gnupg
    state: directory
    group: jenkins
    owner: jenkins
    mode: 0700

- name: Add gpg-agent conf file
  copy:
    src: ../files/gpg-agent.conf
    dest: /home/jenkins/.gnupg/gpg-agent.conf
    group: jenkins
    owner: jenkins
    mode: 0600
  notify:
    - restart jenkins

- name: Kill gpg-agent
  command: gpgconf --kill gpg-agent
