---
- name: Install OpenJDK JRE 8
  apt: name=openjdk-8-jre state=latest update_cache=yes
  notify:
    - restart jenkins

- name: Install tools
  tags: [apt]
  apt:
    update_cache: yes
    state: present
    name: "{{ dist_tools }}"
  notify:
    - restart jenkins

- name: Install pinned dist packages
  tags: [apt]
  apt:
    update_cache: yes
    state: present
    name:
      - wkhtmltopdf=0.12.2.4-1
      - jq=1.5+dfsg-1ubuntu0.1
      - nodejs=4.*

- name: Install AWS cli
  pip:
    name: awscli==1.16.109
    state: present

- name: Create AWS cli config folder
  file:
    path: ~/.aws
    state: directory
    owner: jenkins
    group: jenkins
    mode: u=rwx
  become: true
  become_user: jenkins

- name: Create AWS cli config file
  template:
    src: aws_config.j2
    dest: ~/.aws/config
    owner: jenkins
    group: jenkins
    mode: u=rw
  become: true
  become_user: jenkins
  vars:
    assume_roles: "{{ cloudtrail_validate_logs_roles }}"

- name: Install rbenv and pyenv
  git: repo={{ item.repo }} dest=/var/lib/jenkins/{{ item.path }}
  with_items:
    - {repo: "https://github.com/sstephenson/rbenv.git", path: ".rbenv"}
    - {repo: "https://github.com/sstephenson/ruby-build.git", path: ".rbenv/plugins/ruby-build"}
    - {repo: "https://github.com/carsomyr/rbenv-bundler.git", path: ".rbenv/plugins/bundler"}
    - {repo: "https://github.com/yyuu/pyenv.git", path: ".pyenv"}
    - {repo: "https://github.com/yyuu/pyenv-virtualenv.git", path: ".pyenv/plugins/pyenv-virtualenv"}
  become: yes
  become_user: jenkins

- name: Add .rbenv and .pyenv to PATH
  lineinfile:
    dest: /var/lib/jenkins/.bash_profile
    create: yes
    regexp: 'export PATH="/var/lib/jenkins/{{ item.path }}/bin'
    line: 'export PATH="/var/lib/jenkins/{{ item.path }}/bin:$PATH" && export {{ item.env_var }}="/var/lib/jenkins/{{ item.path }}"'
    owner: jenkins
    group: jenkins
  with_items:
    - {path: ".rbenv", env_var: "RBENV_ROOT"}
    - {path: ".pyenv", env_var: "PYENV_ROOT"}

- name: Add rbenv and pyenv init
  lineinfile:
    dest: /var/lib/jenkins/.bash_profile
    regexp: '{{ item.name }} init'
    line: 'eval "$({{ item.name }} init -)"'
    owner: jenkins
    group: jenkins
  with_items:
    - {name: "rbenv"}
    - {name: "pyenv"}

- name: Install Python build requirements
  apt:
    name: libbz2-dev

- name: Install Python 3 using pyenv
  shell: |
    source ~/.bash_profile
    pyenv install -s 3.6.2
    pyenv shell 3.6.2
    pip install -U pip virtualenv
  args:
    executable: /bin/bash
  become: yes
  become_user: jenkins

- name: Add gpg-agent conf directory
  file: path=/var/lib/jenkins/.gnupg state=directory owner=jenkins group=jenkins

- name: Add gpg-agent conf file
  copy:
    src: ../files/gpg-agent.conf
    dest: /var/lib/jenkins/.gnupg/gpg-agent.conf
    group: jenkins
    owner: jenkins
  notify:
    - restart jenkins

- name: Kill gpg-agent
  command: gpgconf --kill gpg-agent

# TODO: Stop installing PhantomJS when it has been fully removed from our tests
- name: Download PhantomJS
  get_url:
    url: "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"
    checksum: md5:1c947d57fce2f21ce0b43fe2ed7cd361
    dest: /usr/local/src/phantomjs-2.1.1-linux-x86_64.tar.bz2

- name: Unarchive PhantomJS
  unarchive:
    src: /usr/local/src/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /usr/local/src
    copy: no

- name: Install PhantomJS binary
  file: src=/usr/local/src/phantomjs-2.1.1-linux-x86_64/bin/phantomjs dest=/usr/local/bin/phantomjs state=link
