---
- name: Install OpenJDK JRE 8
  apt: name=openjdk-8-jre state=latest update_cache=yes
  notify:
    - restart jenkins

- name: Install tools
  tags: [apt]
  apt:
    update_cache: yes
    state: present
    name: "{{ dist_tools }}"
  notify:
    - restart jenkins

- name: Install pinned dist packages
  tags: [apt]
  apt:
    update_cache: yes
    state: present
    name:
      - wkhtmltopdf=0.12.*
      - jq=1.5+dfsg-*
      - nodejs=8.*
      - libssl1.0-dev

- name: Update Python 3 pip
  pip:
    name:
      - pip
    state: latest

- name: Install AWS cli
  pip:
    name: awscli==1.16.109
    state: present

- name: Create AWS cli config folder
  file:
    path: ~/.aws
    state: directory
    owner: jenkins
    group: jenkins
    mode: u=rwx
  become: true
  become_user: jenkins

- name: Create AWS cli config file
  template:
    src: aws_config.j2
    dest: ~/.aws/config
    owner: jenkins
    group: jenkins
    mode: u=rw
  become: true
  become_user: jenkins
  vars:
    assume_roles: "{{ cloudtrail_validate_logs_roles }}"

- name: Install rbenv
  git: repo={{ item.repo }} dest=/var/lib/jenkins/{{ item.path }}
  with_items:
    - {repo: "https://github.com/sstephenson/rbenv.git", path: ".rbenv"}
    - {repo: "https://github.com/sstephenson/ruby-build.git", path: ".rbenv/plugins/ruby-build"}
    - {repo: "https://github.com/carsomyr/rbenv-bundler.git", path: ".rbenv/plugins/bundler"}
  become: yes
  become_user: jenkins

- name: Add .rbenv to PATH
  lineinfile:
    dest: /var/lib/jenkins/.bash_profile
    create: yes
    regexp: 'export PATH="/var/lib/jenkins/.rbenv/bin'
    line: 'export PATH="/var/lib/jenkins/.rbenv/bin:$PATH" && export RBENV_ROOT="/var/lib/jenkins/.rbenv"'
    owner: jenkins
    group: jenkins

- name: Add rbenv init
  lineinfile:
    dest: /var/lib/jenkins/.bash_profile
    regexp: 'rbenv init'
    line: 'eval "$(rbenv init -)"'
    owner: jenkins
    group: jenkins

- name: Add gpg-agent conf directory
  file: path=/var/lib/jenkins/.gnupg state=directory owner=jenkins group=jenkins

- name: Add gpg-agent conf file
  copy:
    src: ../files/gpg-agent.conf
    dest: /var/lib/jenkins/.gnupg/gpg-agent.conf
    group: jenkins
    owner: jenkins
  notify:
    - restart jenkins

- name: Kill gpg-agent
  command: gpgconf --kill gpg-agent

# TODO: Stop installing PhantomJS when it has been fully removed from our tests
- name: Download PhantomJS
  get_url:
    url: "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"
    checksum: md5:1c947d57fce2f21ce0b43fe2ed7cd361
    dest: /usr/local/src/phantomjs-2.1.1-linux-x86_64.tar.bz2

- name: Unarchive PhantomJS
  unarchive:
    src: /usr/local/src/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /usr/local/src
    copy: no

- name: Install PhantomJS binary
  file: src=/usr/local/src/phantomjs-2.1.1-linux-x86_64/bin/phantomjs dest=/usr/local/bin/phantomjs state=link
