---

# If Github OAuth has been configured the admin user is not available and stops working, we use the jenkins github user
# If Github OAuth has not been configured we only have the admin user

- name: Check if Github OAuth is set up yet so we can use the correct credentials
  uri:
    user: "{{ jenkins_api_user }}"
    password: "{{ jenkins_api_user_github_personal_access_token }}"
    url: "http://localhost:8080/api/json"
    force_basic_auth: yes
  register: auth_test
  ignore_errors: yes
  retries: 10
  delay: 5

- name: Set credentials to jenkins github user if it exists
  set_fact:
    plugins_username: "{{ jenkins_api_user }}"
    plugins_password: "{{ jenkins_api_user_github_personal_access_token }}"
  when: not auth_test.failed

- name: Set credentials to admin user if jenkins github user does not exist
  set_fact:
    plugins_username: "{{ jenkins_admin_user }}"
    plugins_password: "{{ jenkins_admin_password }}"
  when: auth_test.failed

- name: Install plugins
  jenkins_plugin:
    jenkins_home: "{{ jenkins_data_dir }}"
    name: "{{ item }}"
    url_username: "{{ plugins_username }}"
    url_password: "{{ plugins_password }}"
  with_items: "{{ jenkins_plugins }}"

- name: Restart Jenkins to activate new plugins
  service: name=jenkins state=restarted

- name: Wait for Jenkins to become available
  wait_for: port=8080
