---
- name: copy a requirements file with pinned Python dependencies
  copy:
    src: ../../../../requirements-jenkins-job-builder.txt
    dest: /tmp/jenkins-jobs-python-requirements.txt
    force: yes

- name: Install all our dependencies
  pip:
    requirements: /tmp/jenkins-jobs-python-requirements.txt

- name: Create /var/lib/jenkins/jenkins_jobs/definitions
  file: path=/var/lib/jenkins/jenkins_jobs/definitions state=directory recurse=yes owner=jenkins

- name: Create jenkins job config directory
  file:
    path: /etc/jenkins_jobs
    state: directory
    owner: jenkins

- name: Deploy jenkins_jobs.ini
  template: dest=/etc/jenkins_jobs/jenkins_jobs.ini src=jenkins_jobs.ini.j2 owner=jenkins

- name: Clone digitalmarketplace-credentials repository
  tags: [credentials-repo]
  git:
    repo: "git@github.com:alphagov/digitalmarketplace-credentials.git"
    dest: /var/lib/jenkins/digitalmarketplace-credentials
  become: yes
  become_user: jenkins

- name: Remove deleted or renamed definitions
  synchronize:
    src: '../../../../job_definitions/'
    dest: '/var/lib/jenkins/jenkins_jobs/definitions'
    delete: yes
    archive: no
    recursive: yes
    rsync_opts: ['--ignore-existing']

- name: Upload jenkins jobs definitions
  template: src={{ item }} dest=/var/lib/jenkins/jenkins_jobs/definitions/ owner=jenkins
  with_fileglob:
    - '../../../../job_definitions/{{ jobs }}.yml'

- name: Test job definitions before updating (as jenkins user)
  command: jenkins-jobs test /var/lib/jenkins/jenkins_jobs/definitions
  become: yes
  become_user: jenkins

- name: Update job definitions (as jenkins user)
  command: jenkins-jobs update /var/lib/jenkins/jenkins_jobs/definitions
  become: yes
  become_user: jenkins