---
- name: Letsencrypt Python client
  git: dest=/opt/certbot clone=yes repo=https://github.com/certbot/certbot force=yes

- name: Request certificate file
  shell: executable=/bin/bash /opt/certbot/certbot-auto certonly -m {{ letsencrypt_email }} -d {{ inventory_hostname }} --agree-tos --standalone --expand --standalone-supported-challenges http-01 --keep-until-expiring --non-interactive

- name: Create ssl/certs dir
  file: path=/etc/nginx/ssl/certs mode=755 state=directory owner=root

- name: Create ssl/private dir
  file: path=/etc/nginx/ssl/private mode=700 state=directory owner=root

- name: Copy the TLS certificate
  command: cp /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem /etc/nginx/ssl/certs/cert.pem
  notify: reload nginx

- name: Set TLS cert permissions
  file: path=/etc/nginx/ssl/certs/cert.pem mode=0644 group=ssl-cert
  notify: reload nginx

- name: Copy the TLS key
  command: cp /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem /etc/nginx/ssl/private/privkey.pem
  notify: reload nginx

- name: Set TLS key permissions
  file: path=/etc/nginx/ssl/private/privkey.pem mode=0644 group=ssl-cert
  notify: reload nginx
