---
- include: volume.yml tags=volume
- include: vpn.yml tags=vpn

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Ensure Jenkins is installed.
  apt: pkg=jenkins state=installed

- name: Set Jenkins service boot config
  template: src=jenkins_defaults.j2
            dest=/etc/default/jenkins
            backup=no
  notify: restart jenkins

- name: Copy Jenkins config file
  template: src=jenkins/config.xml.j2
        dest=/data/jenkins/config.xml
        backup=yes
  notify: restart jenkins
  tags: config

- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes

- name: Instal curl
  apt: pkg=curl state=installed

- name: Wait for Jenkins to start up before proceeding.
  shell: curl --head --silent http://{{ jenkins_hostname }}:8080/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://{{ jenkins_hostname }}:8080/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10

- include: plugins.yml tags=plugins
- include: nginx.yml tags=nginx
