---
- import_tasks: bootstrap.yml
  tags: [bootstrap]
- import_tasks: keys.yml
  tags: [keys]
- import_tasks: tools.yml
  tags: [tools]
- import_tasks: nginx.yml
  tags: [nginx]
- import_tasks: jenkins.yml
  tags: [jenkins]
- import_tasks: plugins.yml
  tags: [plugins]
- import_tasks: config.yml  # must come after plugins, otherwise we are configuring plugins that are not installed!
  tags: [config]
- import_tasks: scripts.yml
  tags: [scripts]
- import_tasks: gdrive.yml
  tags: [gdrive]
- import_tasks: docker.yml
  tags: [docker]
- import_tasks: paas.yml
  tags: [paas,cloudfoundry]
- import_tasks: sops.yml
  tags: [sops]
- import_tasks: jobs.yml
  tags: [jobs]
- import_tasks: upgrade_packages.yml
  tags: [upgrade_packages]
- import_tasks: amazon_cloudwatch_agent.yml
  tags: [amazon_cloudwatch_agent]

