---
- import_tasks: 00_amazon_cloudwatch_agent.yml
  tags: [amazon_cloudwatch_agent]
- import_tasks: 00_bootstrap.yml
  tags: [bootstrap]
- import_tasks: 01_keys.yml
  tags: [keys]
- import_tasks: 05_tools.yml
  tags: [tools]
- import_tasks: 05_gdrive.yml
  tags: [gdrive]
- import_tasks: 05_docker.yml
  tags: [docker]
- import_tasks: 05_paas.yml
  tags: [paas,cloudfoundry]
- import_tasks: 05_sops.yml
  tags: [sops]
- import_tasks: 05_nginx.yml
  tags: [nginx]
- import_tasks: 05_jenkins.yml
  tags: [jenkins]
- import_tasks: 06_plugins.yml
  tags: [plugins]
- import_tasks: 07_config.yml  # must come after plugins, otherwise we are configuring plugins that are not installed!
  tags: [config]
- import_tasks: 07_logs.yml
  tags: [logs]
- import_tasks: 10_jobs.yml
  tags: [jobs]
- import_tasks: 99_scripts.yml
  tags: [scripts]
- import_tasks: 99_upgrade_packages.yml
  tags: [upgrade_packages]
